import html2canvas from "html2canvas";

interface NoteData {
  questionText: string;
  note: string;
  subject?: string;
  system?: string;
  timestamp: string;
}

export const exportNotesToPDF = async (notes: NoteData[], testName: string = "Practice Test") => {
  // Create a temporary container for the PDF content
  const container = document.createElement("div");
  container.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 800px;
    padding: 40px;
    background: white;
    font-family: system-ui, -apple-system, sans-serif;
  `;

  // Build HTML content
  container.innerHTML = `
    <div style="text-align: center; margin-bottom: 30px;">
      <h1 style="font-size: 24px; color: #1a1a1a; margin: 0 0 10px 0;">Study Notes</h1>
      <p style="color: #666; font-size: 14px; margin: 0;">${testName} - Exported on ${new Date().toLocaleDateString()}</p>
    </div>
    
    ${notes.map((note, index) => `
      <div style="margin-bottom: 24px; padding: 16px; border: 1px solid #e5e5e5; border-radius: 8px; page-break-inside: avoid;">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 12px;">
          <span style="background: #3b82f6; color: white; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 500;">
            Question ${index + 1}
          </span>
          ${note.subject ? `<span style="color: #666; font-size: 12px;">${note.subject}${note.system ? ` - ${note.system}` : ''}</span>` : ''}
        </div>
        
        <div style="margin-bottom: 12px;">
          <p style="font-size: 14px; color: #1a1a1a; margin: 0; line-height: 1.6;">
            ${note.questionText}
          </p>
        </div>
        
        <div style="background: #f8fafc; padding: 12px; border-radius: 6px; border-left: 3px solid #3b82f6;">
          <p style="font-size: 12px; color: #666; margin: 0 0 4px 0; font-weight: 500;">Your Notes:</p>
          <p style="font-size: 13px; color: #1a1a1a; margin: 0; white-space: pre-wrap; line-height: 1.5;">
            ${note.note}
          </p>
        </div>
      </div>
    `).join('')}
    
    <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e5e5;">
      <p style="color: #999; font-size: 12px; margin: 0;">Generated by MedPrep Study Hub</p>
    </div>
  `;

  document.body.appendChild(container);

  try {
    // Use html2canvas to capture the content
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
    });

    // Convert to blob and download
    canvas.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `${testName.replace(/\s+/g, "_")}_notes_${new Date().toISOString().split("T")[0]}.png`;
        link.click();
        URL.revokeObjectURL(url);
      }
    }, "image/png", 1);

    return { success: true };
  } catch (error) {
    console.error("Error exporting notes:", error);
    return { success: false, error };
  } finally {
    document.body.removeChild(container);
  }
};

// Simple text-based export as fallback
export const exportNotesToText = (notes: NoteData[], testName: string = "Practice Test"): void => {
  let content = `STUDY NOTES\n`;
  content += `${testName}\n`;
  content += `Exported: ${new Date().toLocaleString()}\n`;
  content += `${"=".repeat(50)}\n\n`;

  notes.forEach((note, index) => {
    content += `Question ${index + 1}\n`;
    content += `${"-".repeat(30)}\n`;
    if (note.subject) {
      content += `Subject: ${note.subject}${note.system ? ` | System: ${note.system}` : ''}\n`;
    }
    content += `\n${note.questionText}\n`;
    content += `\nYour Notes:\n${note.note}\n`;
    content += `\n${"=".repeat(50)}\n\n`;
  });

  // Create and download file
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${testName.replace(/\s+/g, "_")}_notes_${new Date().toISOString().split("T")[0]}.txt`;
  link.click();
  URL.revokeObjectURL(url);
};
